name: spectrome
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info: ^0.4.2+7
  shared_preferences: ^0.5.10
  email_validator: ^1.0.5
  camera: ^0.5.8+5
  photo_manager: ^0.5.8
  crypto: ^2.1.5
  path_provider: ^1.6.14
  better_player: ^0.0.13
  firebase_messaging: ^7.0.2
  firebase_crashlytics: ^0.2.1
  flutter_swipe_action_cell: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - assets/images/icon.png
    - assets/images/logo.png
    - assets/images/logo@2x.png
    - assets/images/logo-alt.png
    - assets/images/logo-alt@2x.png
    - assets/images/loading.gif
    - assets/images/default.1.jpg
    - assets/images/default.2.jpg
  
  fonts:
    - family: Primary Regular
      fonts:
      - asset: assets/fonts/font-primary-regular.ttf
    - family: Primary Bold
      fonts:
      - asset: assets/fonts/font-primary-bold.ttf
        weight: 700
    - family: Font Awesome
      fonts:
      - asset: assets/fonts/fa-solid.ttf
    - family: Font Awesome Brand
      fonts:
      - asset: assets/fonts/fa-brand.ttf
    - family: Font Awesome Light
      fonts:
      - asset: assets/fonts/fa-light.ttf
